_target_: utils.llm_client.openai.OpenAIClient

# Using deepseek API
model: deepseek-v4-flash
temperature: 0.7  # temperature for chat completion
api_key: ${oc.env:DEEPSEEK_API_KEY}
base_url: https://api.deepseek.com
